name: talos-workshop

networks:
  talos-workshop:
    driver: bridge
    ipam:
      config:
        - subnet: "172.20.0.0/24"
          gateway: "172.20.0.1"

volumes:
  cp-state:
  worker-state:

services:
  talos-cp:
    image: ghcr.io/siderolabs/talos:v1.7.4
    hostname: talos-cp
    environment:
        - PLATFORM=container
    read_only: true
    privileged: true
    security_opt:
      - seccomp=unconfined
    volumes:
      - type: volume
        target: /var
      - type: volume
        target: /etc/cni
      - type: volume
        target: /etc/kubernetes
      - type: volume
        target: /usr/libexec/kubernetes
      - type: volume
        target: /opt
      - cp-state:/system/state
    tmpfs:
      - /run
      - /system
      - /tmp
    networks:
      talos-workshop:
        ipv4_address: 172.20.0.100

  talos-worker:
    image: ghcr.io/siderolabs/talos:v1.7.4
    hostname: talos-worker
    environment:
        - PLATFORM=container
    read_only: true
    privileged: true
    security_opt:
      - seccomp=unconfined
    volumes:
      - type: volume
        target: /var
      - type: volume
        target: /etc/cni
      - type: volume
        target: /etc/kubernetes
      - type: volume
        target: /usr/libexec/kubernetes
      - type: volume
        target: /opt
      - worker-state:/system/state
    tmpfs:
      - /run
      - /system
      - /tmp
    networks:
      talos-workshop:
        ipv4_address: 172.20.0.150